import { NextPage, GetServerSideProps} from "next";
import { useRouter } from "next/router";
import Head from 'next/head'
import Image from 'next/image'
// Import Components
import Wrapper from 'containers/Wrapper'
import HomeSection from '../templates/HomeSection'
// Import Custom Hooks

import styles from '../styles/Home.module.css'
import { getSupabaseUser } from "services/get-auth-user";


export default function Home() {

  const router = useRouter();


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <ModalPortal>
      </ModalPortal> */}
      <Wrapper>
        <HomeSection />
        {/* <HelloContainer /> */}
      </Wrapper>
      
    </div>
  )
}
